version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/proj_dev
      - SECRET_KEY_BASE=XRHG4JbOq3aJLrhvznOdWNhc8NnXpu1zPuA+qrVDZKtcKgGLfs2sM3owUlZrsToD
      - PHX_HOST=localhost
      - PORT=4000
    restart: always

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proj_dev
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: